//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemBiblioteka.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WypozycalniaEntities : DbContext
    {
        public WypozycalniaEntities()
            : base("name=WypozycalniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Literatura> Literatura { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
        public virtual DbSet<Wydawnictwo> Wydawnictwo { get; set; }
        public virtual DbSet<Wypozyczona_literatura> Wypozyczona_literatura { get; set; }
        public virtual DbSet<Zwrot_literatury> Zwrot_literatury { get; set; }
    }
}
