//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemBiblioteka.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Literatura : INotifyPropertyChanged
    {
        private int id;
        private string kategoria;
        private string tytul;
        private int idAutor;
        private int idWydawnictwo;


        public int Id { get => id; set 
            {
                id = value;
                OnPropertyChanged(nameof(Id));
            }                
        }
        public string Kategoria { get => kategoria; set
            {
                kategoria = value;
                OnPropertyChanged(nameof(Kategoria));
            }
        }
        public string Tytul { get => tytul; set
            {
                tytul = value;
                OnPropertyChanged(nameof(Tytul));
            }
        }
        public int Id_Autor { get => idAutor; set
            {
                idAutor = value;
                OnPropertyChanged(nameof(Id_Autor));
            }
        }
        public int Id_Wydawnictwo { get => Id_Wydawnictwo; set
            {
                idWydawnictwo = value;
                OnPropertyChanged(nameof(Id_Wydawnictwo));
            }
        }
    
        public virtual Autor Autor { get; set; }
        public virtual Wydawnictwo Wydawnictwo { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;

        public void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
