//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemBiblioteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Literatura
    {
        public int Id { get; set; }
        public string Kategoria { get; set; }
        public string Tytul { get; set; }
        public int Id_Autor { get; set; }
        public int Id_Wydawnictwo { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Wydawnictwo Wydawnictwo { get; set; }
    }
}
