//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemBiblioteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczona_literatura
    {
        public int Id_Uzytkownika { get; set; }
        public int Id_Literatury { get; set; }
        public Nullable<System.DateTime> Data_Wydania { get; set; }
        public int Okres_Wypozyczenia { get; set; }
    
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
