//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemBiblioteka.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Zwrot_literatury : INotifyPropertyChanged
    {
        private int idUzytkownika;
        private int idLiteratury;
        private DateTime dataZwrotu;

        public int Id_Uzytkownika { get => idUzytkownika; set
            {
                idUzytkownika = value;
                OnPropertyChanged(nameof(Id_Uzytkownika));
            }
        }
        public int Id_Literatury { get => idLiteratury; set
            {
                idLiteratury = value;
                OnPropertyChanged(nameof(Id_Literatury));
            }
        }
        public Nullable<System.DateTime> Data_Zwrotu { get => dataZwrotu; set
            {
                dataZwrotu = (DateTime)value;
                OnPropertyChanged(nameof(Data_Zwrotu));
            }
        }
    
        public virtual Uzytkownicy Uzytkownicy { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;

        public void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
